version: "3.8"

services:
  web:
    build: .
    container_name: hrms_app
    command: gunicorn --bind 0.0.0.0:8000 360SolveHRMS.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/static  # Collect static files to serve via Nginx
    ports:
      - "5001:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: HRMDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    depends_on:
      - web
    ports:
      - "4000:8080"  # Nginx listens on port 8080
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Mount the Nginx config file
      - static_volume:/static  # Ensure Nginx can access static files


  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper



volumes:
  pg_data:
  static_volume:
