# Generated by Django 5.1.7 on 2025-03-31 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=True, max_length=150)),
                ('Logo', models.FileField(default=True, upload_to='media/logs/')),
                ('Description', models.CharField(max_length=150, null=True)),
                ('IsDeleted', models.IntegerField(default=0)),
                ('Status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
            ],
            options={
                'db_table': 'MasterModule',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='SubModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=True, max_length=150)),
                ('Module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.mastermodule')),
            ],
            options={
                'db_table': 'SubModule',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groupAcess', models.BooleanField(default=False)),
                ('createdOn', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('roleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.role')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
