# Generated by Django 5.1.7 on 2025-04-02 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=100)),
                ('country_currency', models.CharField(max_length=100)),
                ('country_status', models.CharField(max_length=100)),
                ('isdelete', models.IntegerField()),
            ],
            options={
                'db_table': 'CountryTbl',
            },
        ),
        migrations.CreateModel(
            name='DistrictTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=225)),
                ('districtcode', models.CharField(blank=True, db_column='DistrictCode', max_length=225, null=True)),
            ],
            options={
                'db_table': 'DistrictTbl',
            },
        ),
        migrations.CreateModel(
            name='MasterModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=True, max_length=150)),
                ('Logo', models.FileField(default=True, upload_to='media/logs/')),
                ('Description', models.CharField(max_length=150, null=True)),
                ('IsDeleted', models.IntegerField(default=0)),
                ('Status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
            ],
            options={
                'db_table': 'MasterModule',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='CityTbl',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=255)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('isdelete', models.IntegerField()),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='HRMSapp.districttbl')),
            ],
            options={
                'db_table': 'CityTbl',
            },
        ),
        migrations.CreateModel(
            name='StateTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=255)),
                ('state_status', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('isdelete', models.IntegerField()),
                ('gst_code', models.IntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HRMSapp.countrytbl')),
            ],
            options={
                'db_table': 'StateTbl',
            },
        ),
        migrations.CreateModel(
            name='GroupAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=200)),
                ('legalname', models.CharField(max_length=200)),
                ('shortname', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('contact_mob', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.citytbl')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.countrytbl')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.districttbl')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.statetbl')),
            ],
            options={
                'db_table': 'GroupAdmin',
            },
        ),
        migrations.AddField(
            model_name='districttbl',
            name='state',
            field=models.ForeignKey(db_column='StateId', on_delete=django.db.models.deletion.DO_NOTHING, to='HRMSapp.statetbl'),
        ),
        migrations.CreateModel(
            name='CompanyTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_code', models.CharField(max_length=200)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('localname', models.CharField(max_length=200)),
                ('legalname', models.CharField(max_length=200)),
                ('company_address', models.CharField(max_length=200)),
                ('company_cin', models.CharField(max_length=200)),
                ('company_tin', models.CharField(max_length=200)),
                ('contact_mob', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('company_registration', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.citytbl')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.countrytbl')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.districttbl')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.groupadmin')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.statetbl')),
            ],
            options={
                'db_table': 'CompanyTbl',
            },
        ),
        migrations.CreateModel(
            name='BranchTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=200)),
                ('local_name', models.CharField(max_length=200)),
                ('branch_code', models.CharField(max_length=200)),
                ('legalname', models.CharField(max_length=200)),
                ('branch_address', models.CharField(max_length=200)),
                ('contact_mob', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('company_registeration', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.citytbl')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.companytbl')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.countrytbl')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.districttbl')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.statetbl')),
            ],
            options={
                'db_table': 'BranchTbl',
            },
        ),
        migrations.CreateModel(
            name='SubModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=True, max_length=150)),
                ('IsDeleted', models.IntegerField(default=0)),
                ('Status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('Module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.mastermodule')),
            ],
            options={
                'db_table': 'SubModule',
            },
        ),
        migrations.CreateModel(
            name='SubmoduleLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_value', models.IntegerField(default=0)),
                ('isactive', models.IntegerField(default=1)),
                ('isdeleted', models.IntegerField(default=0)),
                ('submod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.submodule')),
            ],
            options={
                'db_table': 'SubmoduleLimit',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('expirydate', models.DateTimeField(auto_now=True)),
                ('Module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.mastermodule')),
                ('Sub_Module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.submodule')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.branchtbl')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.companytbl')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.groupadmin')),
            ],
            options={
                'db_table': 'Subscription',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groupAcess', models.BooleanField(default=False)),
                ('createdOn', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.role')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
