# Generated by Django 5.1.7 on 2025-03-27 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=True, max_length=150)),
                ('Logo', models.FileField(default=True, upload_to='media/logs/')),
                ('IsDeleted', models.IntegerField()),
                ('Status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
            ],
            options={
                'db_table': 'MasterModule',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='SubModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=True, max_length=150)),
                ('Module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.mastermodule')),
            ],
            options={
                'db_table': 'SubModule',
            },
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='superadmin_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='superadmin_permissions', to='auth.permission')),
            ],
            options={
                'db_table': 'SuperAdmin',
            },
        ),
    ]
