# Generated by Django 5.1.7 on 2025-03-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submodule',
            name='IsDeleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submodule',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
        ),
    ]
