# Generated by Django 5.1.7 on 2025-04-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxName', models.CharField(max_length=150, null=True)),
                ('is_deleted', models.BooleanField(default=0)),
                ('Category', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'TaxType',
            },
        ),
        migrations.AddField(
            model_name='districttbl',
            name='district_status',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='districttbl',
            name='isdelete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='districttbl',
            name='short_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mastermodule',
            name='Status',
            field=models.IntegerField(choices=[(1, 'True'), (0, 'False')], default=1),
        ),
    ]
