# Generated by Django 5.1.7 on 2025-04-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherTypeTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'VoucherTypeTbl',
            },
        ),
    ]
