# Generated by Django 5.1.7 on 2025-04-01 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='roleid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.role'),
        ),
    ]
