# Generated by Django 5.1.7 on 2025-03-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermodule',
            name='Description',
            field=models.CharField(default=True, max_length=150, null=True),
        ),
    ]
