# Generated by Django 5.1.7 on 2025-03-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superadmin',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='superadmin',
            name='Password',
        ),
        migrations.AddField(
            model_name='superadmin',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='superadmin_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='superadmin_permissions', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='password',
            field=models.CharField(default=True, max_length=150),
        ),
    ]
