# Generated by Django 5.1.7 on 2025-04-01 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0002_alter_role_id_alter_user_roleid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='roleid',
            new_name='role',
        ),
    ]
