# Generated by Django 5.1.7 on 2025-04-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0002_taxtype_districttbl_district_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastermodule',
            name='Status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='submodule',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
