# Generated by Django 5.1.7 on 2025-04-02 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0002_vouchertypetbl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupadmin',
            name='address',
        ),
        migrations.RemoveField(
            model_name='groupadmin',
            name='description',
        ),
        migrations.RemoveField(
            model_name='groupadmin',
            name='groupname',
        ),
        migrations.RemoveField(
            model_name='groupadmin',
            name='legalname',
        ),
        migrations.RemoveField(
            model_name='groupadmin',
            name='shortname',
        ),
        migrations.AddField(
            model_name='groupadmin',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='groupadmin',
            name='fname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='groupadmin',
            name='noe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='groupadmin',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='groupadmin',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Groupmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=200)),
                ('legalname', models.CharField(max_length=200)),
                ('shortname', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('contact_mob', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.citytbl')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.countrytbl')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.districttbl')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.statetbl')),
            ],
            options={
                'db_table': 'Groupmaster',
            },
        ),
        migrations.AlterField(
            model_name='companytbl',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.groupmaster'),
        ),
    ]
