# Generated by Django 5.1.7 on 2025-03-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0002_mastermodule_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastermodule',
            name='Description',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
