# Generated by Django 5.1.7 on 2025-04-03 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0003_alter_mastermodule_status_alter_submodule_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('is_deleted', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'TaxCategory',
            },
        ),
        migrations.AlterField(
            model_name='taxtype',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.taxcategory'),
        ),
    ]
