# Generated by Django 5.1.7 on 2025-04-01 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0002_submodule_isdeleted_submodule_status'),
        ('HRMSapp', '0003_rename_roleid_user_role'),
    ]

    operations = [
    ]

