# Generated by Django 5.1.7 on 2025-04-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0003_remove_groupadmin_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citytbl',
            name='isdelete',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='citytbl',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='countrytbl',
            name='country_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='countrytbl',
            name='country_currency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='countrytbl',
            name='country_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='countrytbl',
            name='isdelete',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statetbl',
            name='isdelete',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statetbl',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='statetbl',
            name='state_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='statetbl',
            name='state_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
