# Generated by Django 5.1.7 on 2025-04-03 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0004_taxcategory_alter_taxtype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxtype',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.taxcategory'),
        ),
    ]
