# Generated by Django 5.1.7 on 2025-04-01 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0004_merge_20250401_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmoduleLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_value', models.IntegerField(default=1)),
                ('isactive', models.IntegerField(default=1)),
                ('isdeleted', models.IntegerField(default=0)),
                ('submod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.submodule')),
            ],
            options={
                'db_table': 'SubmoduleLimit',
            },
        ),
    ]
