# Generated by Django 5.1.7 on 2025-03-26 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0004_module'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='module',
            table='module',
        ),
        migrations.AlterModelTable(
            name='role',
            table='Role',
        ),
        migrations.AlterModelTable(
            name='superadmin',
            table='SuperAdmin',
        ),
    ]
