# Generated by Django 5.1.7 on 2025-03-26 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0005_alter_module_table_alter_role_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=True, max_length=150)),
                ('Limit', models.IntegerField()),
                ('Module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.module')),
            ],
            options={
                'db_table': 'SubModule',
            },
        ),
    ]
