# Generated by Django 5.1.7 on 2025-04-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0005_submodulelimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submodulelimit',
            name='limit_value',
            field=models.IntegerField(default=0),
        ),
    ]
