# Generated by Django 5.1.7 on 2025-03-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0006_submodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='Logo',
            field=models.FileField(default=True, upload_to='media/logs/'),
        ),
        migrations.AddField(
            model_name='module',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Pending')], default=1),
        ),
    ]
