# Generated by Django 5.1.7 on 2025-03-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0007_module_logo_module_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Module',
            new_name='MasterModule',
        ),
        migrations.AddField(
            model_name='submodule',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
        ),
    ]
